package nfsserve

import (
	"testing"
)

// A file must report the same fileid however it is reached.
//
// The fileid stands in for an inode number, and the Linux client uses it to
// decide whether a filehandle still names the file it named before. When the
// number changes under a handle the client concludes the file was replaced,
// marks the inode stale, and every later operation on it fails with ESTALE --
// generated by the CLIENT, with the server reporting nothing wrong. That is the
// shape of the reported linker failure: `test/integration.sh` section 15d shows
// the server answering every request while `ld` dies with "Stale file handle",
// and instrumenting the server showed no handle it could not resolve.
//
// This package synthesises the number, because Windows exposes no inode through
// os.FileInfo (see fileID in attrs.go). Synthesising it puts the burden here: it
// has to be the same for one file no matter which call produced the FileInfo,
// and the calls do not agree on how they spell a path.
func TestFileIDIsStableHoweverTheFileIsReached(t *testing.T) {
	dir := t.TempDir()
	r := NewRegistry(DefaultAttrs)
	if _, err := r.RegisterCWD(dir); err != nil {
		t.Fatal(err)
	}
	target := mustMount(t, serve(t, r), "/cwd")

	f, err := target.OpenFile("p2", 0o644)
	if err != nil {
		t.Fatalf("OpenFile: %v", err)
	}
	if _, err := f.Write([]byte("hello\n")); err != nil {
		t.Fatalf("write: %v", err)
	}
	f.Close()

	// How a lookup sees it: the server is asked to stat one name.
	viaLookup, err := target.Getattr("p2")
	if err != nil {
		t.Fatalf("getattr: %v", err)
	}

	// How a directory listing sees it: the server joins the directory and the
	// entry name itself. Same file, a different route to the same FileInfo.
	entries, err := target.ReadDirPlus(".")
	if err != nil {
		t.Fatalf("readdirplus: %v", err)
	}
	var viaReadDir uint64
	var found bool
	for _, e := range entries {
		if e.FileName == "p2" {
			viaReadDir, found = e.FileId, true
		}
	}
	if !found {
		t.Fatal("p2 was not in the directory listing")
	}

	if viaLookup.Fileid != viaReadDir {
		t.Errorf("fileid differs by route: getattr %d, readdirplus %d\n"+
			"the client reads that as the file having been replaced, and every "+
			"open descriptor on it goes stale",
			viaLookup.Fileid, viaReadDir)
	}
}
