package nfsserve

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"

	nfsfile "github.com/willscott/go-nfs/file"

	"github.com/lhns/remote-docker/core/workspace"
)

// A file must report the same fileid however it is reached.
//
// The fileid stands in for an inode number, and the Linux client uses it to
// decide whether a filehandle still names the file it named before. When the
// number changes under a handle the client concludes the file was replaced,
// marks the inode stale, and every later operation on it fails with ESTALE --
// generated by the CLIENT, with the server reporting nothing wrong. That is the
// shape of the reported linker failure: the server answered every request while
// `ld` died with "Stale file handle", and instrumenting the server showed no
// handle it could not resolve.
func TestFileIDIsStableHoweverTheFileIsReached(t *testing.T) {
	dir := t.TempDir()
	r := NewRegistry(DefaultAttrs)
	if _, err := r.RegisterCWD(dir); err != nil {
		t.Fatal(err)
	}
	target := mustMount(t, serve(t, r), "/cwd")

	f, err := target.OpenFile("p2", 0o644)
	if err != nil {
		t.Fatalf("OpenFile: %v", err)
	}
	if _, err := f.Write([]byte("hello")); err != nil {
		t.Fatalf("write: %v", err)
	}
	f.Close()

	// How a lookup sees it: the server is asked to stat one name.
	viaLookup, err := target.Getattr("p2")
	if err != nil {
		t.Fatalf("getattr: %v", err)
	}

	// How a directory listing sees it: the server joins the directory and the
	// entry name itself. Same file, a different route to the same FileInfo.
	entries, err := target.ReadDirPlus(".")
	if err != nil {
		t.Fatalf("readdirplus: %v", err)
	}
	var viaReadDir uint64
	var found bool
	for _, e := range entries {
		if e.FileName == "p2" {
			viaReadDir, found = e.FileId, true
		}
	}
	if !found {
		t.Fatal("p2 was not in the directory listing")
	}

	if viaLookup.Fileid != viaReadDir {
		t.Errorf("fileid differs by route: getattr %d, readdirplus %d",
			viaLookup.Fileid, viaReadDir)
	}
}

// The same file, reached by two different SPELLINGS of its path.
//
// This is what a path hash cannot survive, and it is what the kernel caught:
//
//	NFS: server error: fileid changed
//	fsid 0:54: expected fileid 0x1548a05f1dee82e0, got 0xd8adad186b880beb
//
// One file has more than one spelling, and every one of them has to report the
// same fileid or the client decides the file was replaced. A chroot is the
// cheapest way to produce a second spelling: inside, the file is "p2"; from the
// share root it is "sub/p2". go-nfs chroots per mount, so this is the ordinary
// case rather than a contrived one.
//
// Hashing the path fails this. The real inode passes it by construction, which
// is the fix -- the hash was the fallback for Windows, which has no inode to
// report, and was never right anywhere else.
func TestFileIDSurvivesADifferentSpellingOfThePath(t *testing.T) {
	dir := t.TempDir()
	r := NewRegistry(DefaultAttrs)
	if _, err := r.RegisterCWD(dir); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "sub", "p2"), []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}

	share, _, ok := r.Lookup(workspace.ExportCWD)
	if !ok {
		t.Fatal("the working directory share is not registered")
	}

	// Asserted on every platform, deliberately. Unix has the inode and Windows
	// has NTFS's File Reference Number, so there is no platform this project
	// ships on where the answer is allowed to be "it cannot be stable here".
	osPath := filepath.Join(dir, "sub", "p2")
	probe, err := os.Stat(osPath)
	if err != nil {
		t.Fatal(err)
	}
	if _, _, ok := inodeOf(probe, osPath); !ok {
		t.Fatalf("no file identity on %s, so the fileid falls back to hashing "+
			"the path and cannot be stable across spellings", runtime.GOOS)
	}

	outer, err := share.fs.Lstat("sub/p2")
	if err != nil {
		t.Fatalf("stat from the share root: %v", err)
	}
	sub, err := share.fs.Chroot("sub")
	if err != nil {
		t.Fatalf("chroot: %v", err)
	}
	inner, err := sub.Lstat("p2")
	if err != nil {
		t.Fatalf("stat from inside the subdirectory: %v", err)
	}

	outerID := outer.Sys().(*nfsfile.FileInfo).Fileid
	innerID := inner.Sys().(*nfsfile.FileInfo).Fileid
	if outerID != innerID {
		t.Errorf("one file reported two fileids: %#x as sub/p2, %#x as p2 -- "+
			"the client reads that as the file having been replaced, and every "+
			"open descriptor on it goes stale", outerID, innerID)
	}
}
