#!/usr/bin/env bash
#
# Writes THIRD-PARTY-NOTICES.md: every module linked into a released binary,
# with its licence text.
#
# Apache-2.0 section 4(d) asks a redistributor to carry the attribution of what
# it redistributes, and the seven MPL-2.0 components in the graph (HashiCorp,
# reached through buildx) ask for it outright: MPL section 3.3 allows an MPL
# file inside a larger work under other terms only if recipients are told. A
# binary is a redistribution, so the archives need this file.
#
# LINKED, not required: `go list -deps` walks what the binary actually contains,
# where `go list -m all` walks the module graph and lists hundreds of modules
# that no code reaches. Nothing is owed for a module that was never compiled in.
#
# Run by .goreleaser.yaml before it builds. The output is generated and not
# committed.
set -euo pipefail

cd "$(dirname "$0")/.."
out="THIRD-PARTY-NOTICES.md"

# Every binary that ships in an archive. A module reached by either one is
# listed once: the file is a superset, which is the safe direction.
targets=("client:./cmd/remote-docker" "agent:./cmd/remote-dockerd")

modules=""
for target in "${targets[@]}"; do
	module="${target%%:*}"
	main="${target#*:}"
	modules+=$(
		cd "$module" &&
			go list -deps -f '{{if .Module}}{{.Module.Path}}	{{.Module.Version}}	{{.Module.Dir}}{{end}}' "$main"
	)$'\n'
done

# Ours is not third party, and the standard library carries the Go licence,
# which is in every module directory it needs to be.
modules=$(printf '%s' "$modules" | grep -v '^github.com/lhns/remote-docker' | grep -v '^[[:space:]]*$' | sort -u)

{
	echo "# Third-party notices"
	echo
	echo "This distribution links the modules below. Each is listed with the version"
	echo "linked and the licence text shipped with it. Generated by"
	echo "\`scripts/third-party-notices.sh\`; do not edit."
	echo
} >"$out"

count=0
missing=()
while IFS=$'\t' read -r path version dir; do
	[ -n "$path" ] || continue
	# go prints native paths, and a Windows one is not a path to `cat`.
	dir=${dir//\\//}

	files=$(find "$dir" -maxdepth 1 -type f \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' \) | sort)
	if [ -z "$files" ]; then
		missing+=("$path")
		continue
	fi

	{
		echo "## $path"
		echo
		echo "Version: \`$version\`"
		echo
		while IFS= read -r file; do
			echo "\`\`\`"
			cat "$file"
			echo "\`\`\`"
			echo
		done <<<"$files"
	} >>"$out"
	count=$((count + 1))
done <<<"$modules"

# A module with no licence file is a licence question, not a missing file, so
# it stops the release rather than being left out of the notices quietly.
if [ ${#missing[@]} -gt 0 ]; then
	echo "third-party-notices: no licence file found for:" >&2
	printf '  %s\n' "${missing[@]}" >&2
	exit 1
fi

echo "third-party-notices: $count modules in $out"
